services:
  - type: web
    name: pkb-wanime-api # Name of the service
    env: docker
    repo: https://github.com/parthkabanda/api.consumet.org.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000
